@port = 3001
@default = http://localhost:{{port}}

#### Get Single Blog
GET {{default}}/api/blog/629528fafa16a636e7d2d262

#### Get All Blogs
GET {{default}}/api/blog

#### Create New Blog
POST {{default}}/api/blog
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIjMSIsImlkIjoiNjI5NjViMGYzNjRhZDRhMjY2NDBmM2ZlIiwiaWF0IjoxNjU0MDIwOTI1fQ.nmpuJOgygFAnkfLrjfIx3ASEP58A0x5seSIQu8FnoHQ 

{ 
  "background": "https://lesley.edu/sites/default/files/styles/full_width_gallery_1x_wide/public/2021-06/illustration-program-anna-hughes.jpg?itok=iWTJvXBy",
  "title": "ForthBlog",
  "category": "Fashion",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
  "likes": 0,
  "content": "Lorem ipsum dolor sit amet. Et atque commodi quo assumenda omnis et voluptas magni. Cum quisquam dolores sit amet sunt aut rerum debitis sed amet soluta. Aut maxime obcaecati ut consequuntur consequatur 33 molestiae ratione et sapiente similique et esse internos est dolorem error! Sed tenetur praesentium et officia fuga eum iusto assumenda et nemo molestiae sed consequatur iusto est error labore vel voluptatum ullam.",
  "date": "May 1st, 2022"
}


#### Getting Single User
GET {{default}}/api/user/6294e6aea5079e4135785998

#### Get All Users
GET {{default}}/api/user

#### Creating New User
POST {{default}}/api/user 
Content-Type: application/json

{
  "avatar": "http://cdn.onlinewebfonts.com/svg/img_264570.png",
  "username": "user#1",
  "name": "Jan",
  "password": "user#1"
}

#### User Log In
POST {{default}}/api/login
Content-Type: application/json 

{
  "username": "user#1",
  "password": "user#1"
}